### ISSUE TITLE
Card swipe

### ISSUE THREAD

**Issue by richardaum** [Polymer/paper-card#3]
Is possibile to implement a swipe interaction to cards to allow dismissing cards?

**Comment by notwaldorf** [comment]
Ah, yes. Sorry, this completely fell off my radar. 
I think we want a `<iron-swipeable-container>` or something that would allow you to swipe any of its children. I'll start looking into it.

**Comment by notwaldorf** [comment]
@richardaum Just realized you left this comment on the 0.5. card, and my response applies to the 1.0 cards -- in 0.5, cards are swipeable already (check the demo)
